# Generated by Django 3.2 on 2021-04-19 18:19

import datetime
from django.db import migrations, models
import images.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('upload_date', models.DateTimeField(default=datetime.datetime.now)),
                ('file', models.ImageField(blank=True, upload_to=images.models.get_file_path)),
            ],
        ),
    ]
