# Generated by Django 3.2 on 2021-04-20 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_alter_savedimage_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='thumbnail',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
