# Generated by Django 3.2 on 2021-04-20 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0008_image_thumbnail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-id']},
        ),
        migrations.RenameField(
            model_name='image',
            old_name='user',
            new_name='uploader',
        ),
    ]
